2022-12-07 16:03:36,812 (9919/MainThread) litecli.main ERROR - sql: 'select count(id) as counts, pic_name from pictures group by pic_name where counts > 1;', error: OperationalError('near "where": syntax error')
2022-12-07 16:03:36,813 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "where": syntax error\n'
2022-12-07 16:03:52,978 (9919/MainThread) litecli.main ERROR - sql: 'select count(id) as counts, pic_name from pictures where counts > 1 group by pic_name;', error: OperationalError('misuse of aggregate: count()')
2022-12-07 16:03:52,979 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: misuse of aggregate: count()\n'
2022-12-07 16:04:04,937 (9919/MainThread) litecli.main ERROR - sql: 'select count(id) as counts, pic_name from pictures where count(id) > 1 group by pic_name;', error: OperationalError('misuse of aggregate: count()')
2022-12-07 16:04:04,937 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: misuse of aggregate: count()\n'
2022-12-07 16:12:03,574 (9919/MainThread) litecli.main ERROR - sql: 'create index pic_name on pictures;', error: OperationalError('incomplete input')
2022-12-07 16:12:03,575 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: incomplete input\n'
2022-12-07 16:12:20,824 (9919/MainThread) litecli.main ERROR - sql: 'create index pic_name on pictures pic_name;', error: OperationalError('near "pic_name": syntax error')
2022-12-07 16:12:20,824 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "pic_name": syntax error\n'
2022-12-07 16:12:32,849 (9919/MainThread) litecli.main ERROR - sql: "create index 'pic_name' on pictures 'pic_name';", error: OperationalError('near "\'pic_name\'": syntax error')
2022-12-07 16:12:32,849 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "\'pic_name\'": syntax error\n'
2022-12-07 16:12:37,461 (9919/MainThread) litecli.main ERROR - sql: "create index 'pic_name' on pictures pic_name;", error: OperationalError('near "pic_name": syntax error')
2022-12-07 16:12:37,461 (9919/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 129, in run\n    for result in special.execute(cur, sql):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/main.py", line 447, in one_iteration\n    for title, cur, headers, status in res:\n  File "/opt/homebrew/lib/python3.10/site-packages/litecli/sqlexecute.py", line 133, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "pic_name": syntax error\n'
